# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='20', max_length=20),
            preserve_default=False,
        ),
    ]
