# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content',
        ),
    ]
