# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='price',
            field=models.CharField(default='200', max_length=200),
            preserve_default=False,
        ),
    ]
