# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190111_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pxw_goods',
            },
        ),
    ]
