# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='shoesname',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
