# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.list_goods'),
        ),
    ]
