# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190116_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=False),
        ),
    ]
