# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190118_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
    ]
