# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
